# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
commands:
  print_pipeline_id:
    description: "A very simple command to print workflow ID"
    parameters:
      to:
        type: string
        default: echo $CIRCLE_WORKFLOW_ID
    steps:
      - run: echo << parameters.to >>
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  print_command:
    docker:
    - image: cimg/base:stable
    steps:
      - print_pipeline_id
  save_to_workspace:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Output command to a file"
          command: echo "Hello World!!!!!!!!" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt
  print_output_file:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: "Print from workspace"
          command: cat ~/output.txt

      
  

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - print_command
      - save_to_workspace
      - print_output_file:
          requires:
            - save_to_workspace

